# Generated by Django 3.1.2 on 2020-10-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201011_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Принимает заказы?'),
        ),
    ]
