# Generated by Django 3.1.2 on 2020-11-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Значение'),
        ),
    ]
